[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "8e93bce1e066fdedad4c29e66ef82922a9f25ea6"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "69e3a7c5af4caee467de9104efcf81cbb9b8004a8b72d24d192a9446aba60e3d"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "fbfff873616eece4913239ee650d88dd3fabc7b3"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "5545814b4e5110f9ea3f7974b48f5ca40df2eda1248bb155226c2afd2cc8ad57"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "63176e86dabfb065aaa09d5eee0d748bc56d64da"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "56a4238ea59738248c3071578ae05417df02c565f2d3e4b0e855acbb0a550e22"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "eae6a8752c33163a3afd5eed0ae7cf5720201985"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "2a132d391141c031103e8525c92641b9846ae416df97da6a2c025995d2886774"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "94d04293eec31e952976dcd5ab98d5c8bf32f7fb"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "3e6f0788fc9eb264c09179b9710794942e5f9c47c578ecbfb5c0ab8514b49557"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "d5d64876c713e3e7bd32b069290695b79d2591c3"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "2cba00168e11d1636cb573c79bb40797e0dfee7e8e22919293f7d15da2d4d64b"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "10fd9593cb169be4668ff50460b2514b84b495f3"
os = "windows"

    [[LibUV.download]]
    sha256 = "e514047d6ddd87d63174cd2fd3da2af9fd4cdc782ec4a573d66fa20601a5fe22"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "00e52e75e6544a26ab71c207f99f35afaaa7c5a8"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "11e07bef395bceb5e6dda9894dc65d2990aef3778a6c395881f459e7a3cd8f92"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "7ab551ca1e935b7c5c1b0bdd315be56594d9656e"
os = "macos"

    [[LibUV.download]]
    sha256 = "e0ed59515da931780dbcd857f48663078412b762a6d8fd4fd21ef629e115b09f"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.x86_64-apple-darwin14.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "58f30b6530839a4d6e44c75520829fca4f08809f"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "18e04902d729e8afba342987b64290b75ed523c4b833001958e2e4f010495697"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "9e6a4e6c066c9275fd1b8518be245f6aef367d04"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "b2e8f048d54e757545ae1e534526a8190411145d15bb8c65f9bb3fcd5a325b66"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.x86_64-linux-musl.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "159a9a525037c787999f71d0299072edcc0302c5"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "a562d7aad04e8911d4f75473bd43966a275514307b00e8089a04b5e0b4dd907b"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "8757790f45f5dbb1b4d40f3c7a9f6cbdbff7abc6"
os = "windows"

    [[LibUV.download]]
    sha256 = "282eb9ba1d586d2ec28e9aa97fd0ca35c5f334046e9993b02b67fc809f492436"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+7/LibUV.v2.0.0.x86_64-w64-mingw32.tar.gz"
