[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "da0e260394eed95f287ce7a5c753feaa84f0b4c2"
os = "macos"

    [[LibUV.download]]
    sha256 = "e75b0a6f9d3a926c6ab179200bf7aee0457042caa0ca99d1d42215ec85c3aaa4"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.aarch64-apple-darwin.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "ea75cfd0395035cea0fac36d4a4bad573d6e903c"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "7c5a1d5a8e09f632651b7b04eaeb2a10e4b0f54f3a45ca46208ab687e494213d"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "8ecff627c9659e87037c2a1c515aab3a93168ee8"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "5683905037ebafee442848c27763d3bcc92d62fe154275223c5b932496a35074"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ff5cf0d75b0e7d29686b9b315b8556920ac97dc8"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "8ac07b5310eb945b50329d0c7b366a30e73d3e79a87a9ade2426fa2fe34d451a"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "64d00e334f6417189210caff5e13ec874545464d"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "e908c38b7faa402f1d2686f0a2e09fb5a5ddad811ff3240448b6cfe9ac4da75a"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.armv6l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5fc407b7a2020d7c3317d5b4741694ab8869917a"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "ea2266ad77b6f19e635622f2769c6d7e9326572d8ba1197bb7032c7ad5fa5ace"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "305432e82cc76b07b58c81b6533d9282af96fcaa"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "0031ecd4c1075e4dd8321af3ecd4bfb8da698b4766ea79484fb305a5d7ce70e5"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "bf19b9c4a54eee8a92cbbdf4ea749ae4b7e986e4"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "84da83689d814a79451f27c44d23a8f9fd86c316ac47045188a264f30aa0415c"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "9046750b41822929174555824b8e8d10cbb7c00b"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "8475bf032b954e333d30873c4347a7e3cef1cb73f6593da3925deb69485deed4"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "fc5ca5c708af59a9ff31cb323eb709481159301b"
os = "windows"

    [[LibUV.download]]
    sha256 = "0e5fafaf3182d144f867026e622bca1145fa074c4fdd3d0b0030f4c58ad28949"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "29faf16b7a5da98aa9c1f5f7174860866afb11f3"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "28b7b8132f9b73568200541a4b8f1bf739d4e992e26cc1adc98072d33a31f19c"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "4c74b5f3551b867845eebd2756131e27345447aa"
os = "macos"

    [[LibUV.download]]
    sha256 = "172983c819678f67b149d98c4b3cfce33d8afba1c8e5780f2e78809d199fac47"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.x86_64-apple-darwin.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "ab31ee0a3809c7913f2c2b913625cf1d695be0f1"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "bc9378db5408458cd67c14c32239b3e7cf70e3929e8616d0c80ef89d6d124a57"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "ea8d8d70b484ef65e152606bd83f9bd67fc180b6"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibUV.download]]
    sha256 = "44f324cb63bdda57db3206e8335c194d462037ab00dc6bb8b46d1ab63f355d00"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "b2c9b761494274d122992c58e052e0746eaace8c"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "d578e29751266bea5541253ef29176aa711214f008b725e7b6b1d01de3329e42"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.x86_64-linux-musl.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "6f722285cd61fdf961295ae42b12c75d7918a070"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "e8d193291bc917154dbf6a9deb90d585832ba9f456845a7ea8c3e9c8f8129bc4"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.x86_64-unknown-freebsd.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "80ed4814bcfbdb0ae833fd738fdbe8352cd8e650"
os = "windows"

    [[LibUV.download]]
    sha256 = "ae43863d91ff2f397a31447c16538ae97814aa75dbe8f601d621cb979d41bc82"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+11/LibUV.v2.0.1.x86_64-w64-mingw32.tar.gz"
