[[LibUV]]
arch = "i686"
git-tree-sha1 = "7c9ae4955ba8151f9ce4b6eed5edfacf0c453ed1"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "bcb46db8c50e4ed8d98ca607e5703f959aeb073bc8c945c86faf2aed71c67c63"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "50e85a45d6eca2dd96324da7376e6c6c19bb0094"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "327766ccc18e5ad1e7fff5cbaaaa548ae7037c9f53ca1e6f773aaf8ec253189e"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "7b2599a96b8854f0b4ee8b6432447128366a6826"
os = "windows"

    [[LibUV.download]]
    sha256 = "e4d095d0451f92dafc082161eb31eec688b6c0f8666eb2b4c7ceb7705ba56da3"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "170f6f4a32277ffae1232d2b34878ce114a90287"
os = "windows"

    [[LibUV.download]]
    sha256 = "780102dadf385b5fa8056adc99b67d5e061cfb35942c0ab1b38aecbfcf2994de"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.x86_64-w64-mingw32.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "116009d3b3f5a03e6d05b56a1f5ac1a6a2275fb2"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "6eefcca703ffc9bafaea258d555bd929332e049e8fb690c91da353e80a960c0b"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "5f4ddc911dcf6535ebb661c1167c7f9973b276d3"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "f6fffecc76e25483ae723095c3b7e91bce5f7a65fcce3df2795bd2023c9c66de"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "0040e87c0f5fa7bfcdeb48abdc58b6d7b85d1df4"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "17174476beacfdf17afd5366196e416a6609ebc61c18b95a63f096acf7aa5aaf"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "7258f0000865389c94d20c1f2e4238a80f6eab92"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "182e122ce776f4b32be26140384cc38217ff1320cf148994195468f90d7dc20e"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "934eb9de26c494b6dfbe760a0bab946643db7186"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "6dc699290a736b741d733dbfdecb38eb45e4c9daad384b8ff35ed66d5b3f5949"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "40e98b70fe8a6429bd5ea1cfb9b419f76252cd22"
os = "macos"

    [[LibUV.download]]
    sha256 = "43f24fbd4c00818c485ddbe13769f17bb3f98d78fd302d2d8a7bb8cd5a279549"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.x86_64-apple-darwin14.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "fd5a1010256efe3649280df3212cca0dccf40798"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "03cfb009d9e18eb866e5385793861ef67ab8da75d3ab60019ed3a26c37d01dda"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "72eb1ddf9d9cd9b2174362d0a1e630e54b3267e7"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "41038faa269a8a14e9d9298a0695e19c8e074d2b50f5b0471c68021e407632e4"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "a4cd4f92d93158c57e06b1dc7f14cd1064291b22"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "b43e90707153f4486ca3e023efe9b8230803d5cda48cdf72174cb739a7405b4b"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+5/LibUV.v2.0.0.x86_64-linux-musl.tar.gz"
