[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "d49130a5a3d52c19a5368e99ea8616e79b15b066"
os = "macos"

    [[LibUV.download]]
    sha256 = "ed64b922bf6b820206ee89f0eb24085a6ef22f2a1653d96c010b8ab829f9193f"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.aarch64-apple-darwin.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "c48df87c18affad7fe5ed397c7eea55e6e9d9f08"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "e2319e16615e125c5280cf7ab6d4070f19506aa1c358afe6aa3d34c75f391b29"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "e2a69b10f6cbabfa645814467a9e92f3de5c6af9"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "933b7f48b6893480d0df2f8b09af6169aaeccebf09ee76bbf84750d6326cbb57"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "86a471ab87a39520c820b940251cce48997c1d53"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "9b163707fed6e40f0f5d52d1cd79701e767db5eab9ee2af068a9d0e9fa3d13de"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d98d45b21fda868889b94e3edbe04e8c9b9bb44d"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "df1d953eb29c9faa4ad0357ee536ae6e1d79bd3cd674ec9a1bf80d7e5a396454"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.armv6l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0c958abb23b1d533aa40039833652dae4c16c993"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "70f3f5a86d929a5548ceff17a2f03f433d409f571f20ab8a5949c45fc4970ccc"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c04b82fd12f79bec31b314549bc80a78e6b222c"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "eec9562aadbd75effe3c7b3d7bf3dfefd9e2af8aff4ad61e2fbf99136f1eda3c"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "256601f0ccf3812beda619c71175b9b7d5a46625"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "70325ac9bd441d5a5e890a8f42e9cf5c90cacde58ba1e0f5d386e1d239f636d6"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "9a6b9e6278aaceecae06b0c18af1c0944168e550"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "40743ce77b10af0e50babf2adb2179549ea2e630144a9d7d1ee3b75934bb6570"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "ae86e04bf297688478bc6f927db18dce821d3736"
os = "windows"

    [[LibUV.download]]
    sha256 = "55cc1bbb02f05e3e4996d79d892121ce2850388f614c561d03fc6d5299cbc3b5"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "1c97a64f26e84a2ca93a4aa494f464d8de99f6d6"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "cfff485af6460d5703c2b2689def1a7545d42503940ee2fe7b7397aa9c5dcaab"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "2ebe6c542c3137aff529042f0752c3585595ce1a"
os = "macos"

    [[LibUV.download]]
    sha256 = "303290f33d3e1f634fd6ea81b4e9699f341b424f518a0ea0747b8c0a03a38b73"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.x86_64-apple-darwin.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "5117e4647c91c8b907fc6804a2c1f5b73ca5dd64"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "b485d28f12d0f0113d5d61edd74629e2ca9b1a2cc238fe7c92966bb837940bba"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "77565d4799e3cf6fb1312d16fb4ac831296bab26"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibUV.download]]
    sha256 = "710004729275fb8cdd9c43aa3feb6064a7ef9b8e1b6bc2011bbbc6dcce51da88"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "733632c3c117cd8678412f15454bfac99dd32560"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "88e5dc8a030dc0ef9ed3a2754d95fa8643ebd91d71d044f6ce9b2477d7c8a775"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.x86_64-linux-musl.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "2298b71341d7edd8225a3218e0faf49474534411"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "d6fe9c415e7bac073bf12ceee6f8901fc79eb997bba989f802c7a0b6421d208f"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.x86_64-unknown-freebsd.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "a7cbf049ca114cc9aaf8cb8015ae3b2aff1f2a8d"
os = "windows"

    [[LibUV.download]]
    sha256 = "561b45c01e9c338ac053104c0148f056ccf85f8166a9132a5823397202732997"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+15/LibUV.v2.0.1.x86_64-w64-mingw32.tar.gz"
