[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "252150501fb70cff47dd37e8e72c359047414f47"
os = "macos"

    [[LibUV.download]]
    sha256 = "a3f5b9a73f83aa4f225edf5817c736aeda0b2333a668372d20a92b52d5356cd2"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.aarch64-apple-darwin.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "674882ef201ace196861fd9fcdc4376e449e1416"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "e964c217e30c1ac44307169ba2b97ca563a2fd413f8f64cfbf82ad8534ae2caa"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "79ee5c435dc6711d9710a5c43a0c7b322f5bd12d"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "25c13f48b563414d5af5e6a4e7a6b19c30479246c5d8ced7194c332d4beaa977"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "962fabfb376b2c1ade58bc7dae0fe51fdb34620e"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "46ffb75e2b8fd75d219e6b35f8024b0947b0e955f3549d461041ae1eead8f41b"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7722343ecc94b56bff937f4d81e802999ed21992"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "ff897a293e22901caea41582335730a1f629bc2a1d77e28fd05128c0eb23a260"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.armv6l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "57a71085f3b77365563e770fcc1c307c5f6f0659"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "9e56ae00635e28c4bd4962b69cb6561952bc31d80078d1eb4ef1a6ef77988edf"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "708741b30ef0278b1c8ea18de9da5936e61b610d"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "f3dadd17cb0547db53636ea29674bd5c45408aeac35af3845a54f9d824fc77a6"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "6e738b5787363c4a4839e16d92d478b57594b2e2"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "77b996be0fe62d116301b951ec18e65b8d6184ff07ad9d6efd33151f6a081450"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "058a119631247e67d6d9b31a4582aad0169f78f4"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "aa02d700deee4e9ab98a0ca9629f955da6ba9ccb6c5cc1ee56af8483605a6733"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "55f8b3000c75b31ec2cb53b221a7b3cb11f2466c"
os = "windows"

    [[LibUV.download]]
    sha256 = "84de10a490b4f4836964a822972015f844b02b0be3671a7f0f913593b7b1be5d"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "68341a2753de668fe0272d8306db650c22db05fe"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "7062d019008cc06dc57d1053e1beb8dc698817fd873d003cabc427feab3aaf86"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "07b130a23295a5305098ced462fbfbe5c7d79ac6"
os = "macos"

    [[LibUV.download]]
    sha256 = "0d1f62f98a770f083e218e10c009fb9bc01ae37a6b60b8c1f4f32414c04fb9a2"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.x86_64-apple-darwin.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "5277e1f3e9397e265894ec37a4abc67b54fd9af2"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "c172ea69128df958c22161eea0289bfe97383b515655432a56c77584684ee722"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "cd9419ff2edf4d0e10d9f91e6e66969c4808113d"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "c1ea64a082967a85625806fdb34103aa8e8138fba10cc89d2fbefd05a0c29cd9"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.x86_64-linux-musl.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "9c6877a1d440fdb3386a13e203d227234c8f6e8d"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "1e0adbb96429065920955c24eaf14210a78e9786f902dd379e1bb8c6f9ecfc00"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.x86_64-unknown-freebsd.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "cbdaa5855f36e9def770a36b2b0c8f0ac3692730"
os = "windows"

    [[LibUV.download]]
    sha256 = "5b265bf3c6be3fcbe143919192df949de208932f94103044fafa36a4bff70abc"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+3/LibUV.v2.0.1.x86_64-w64-mingw32.tar.gz"
