[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "7c3175130e771561e9c53d6f0c72b28fda91f2b4"
os = "macos"

    [[LibUV.download]]
    sha256 = "3956a38a0a6bb3dc1ba8207c41d18509f1a4b92e567422aeed3d48fb3e08a2b4"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.aarch64-apple-darwin.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "576521dab1a4eca9e3bb32b9508ff9250cc819e1"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "fdc42d756e6ab0f2104aa9296c9affefae11d3cb723eb9d4fa86ad51bed8c058"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "d95617c18db486e039a5dfa63d4a6e8b27e3479a"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "034eb8858fd4e908b25a57ecf82c8780b670bfb3dd21afea68c2b7511ff335ab"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d05661eaa7c73d1dc90a3573c986be6474887159"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "9d4730f897256fdd6bc9b3afdba5144096344657e348f03adad32978c0c58b8a"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5c747d735ac8261602ddd97101af97ee4033ab00"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "c7630b032accbe6286ddba8a9c7fdcaa0b49efb2aa93a7c1436c02580663d68d"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.armv6l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11546fee97d6cf390e9958663f19335aa28e0c0b"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "cd581e90844ecc0e02f75c3da0e7b49f07f937dc667ddc391b78902d0d5da386"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e2d04a254476e9ea65f97cc4445282d2264f1214"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "171541e2cb395e065a17b5ed65f86b0d8e2f23774301bc0ee3e90940548d5c2e"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "9b79333a63c0882fabf8b580ac6758ec7b814162"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "a17bea9a638dab61ae12f88c00ac9076ec0f4861f9938ad16371071b18a9e072"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "43bfcbe1a430360d3774e96287bddaf940fed11a"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "6cc918339adcffc15ef382d49f968dd020aee12c0cdf6dd8fd459bacfe0e768f"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "2cbbfa0c21d22dd2f0f9d40755162bf7d15c4067"
os = "windows"

    [[LibUV.download]]
    sha256 = "25e189dbe901dbcec01778895c0458650b0956e602c3d8b7415931ececc8eb8e"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "e70e25d3bb0a0444a8d92bead814d3fd5c17bd6f"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "bcb1e84f9564eaa209b512fcaf5d0001b480cd6cd348d0ad6c984d5d6b10a9cd"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "480554e794753757f5d85a534473df6b07a86d01"
os = "macos"

    [[LibUV.download]]
    sha256 = "f128660f3c664b0811beb37a014f78c8122fb953fd6e3f4c2e982a127f71a8fa"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.x86_64-apple-darwin.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "92e65cea5a4b02d43d08de463caab14dc2331f4c"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "f036e19cda1d7938251fccd80dd7384dbb76264196ca1b53780df74889416556"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "1f24be8997f6b844f62af25e0eb6d5997bdece17"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "3f1da911cedfcfde0537a6803cf1f22d90f199e2684c99411b83cef767ff41fe"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.x86_64-linux-musl.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "99b87a92db13ea572210e62c90a9d9062bb85579"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "7012cab3a85ac448e3e8ba9ecfbf4474cfc063b4d6d4ce6e8c978bce63be1e2d"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.x86_64-unknown-freebsd.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "a34ecae5be585b7ffe089bbf6804d3cf5562433e"
os = "windows"

    [[LibUV.download]]
    sha256 = "1d85f1b0f769dcde2ef8c31c18247ba6578e688d07d1e7c86f4c1cf14bd7bb21"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+1/LibUV.v2.0.1.x86_64-w64-mingw32.tar.gz"
