[[LibUV]]
arch = "i686"
git-tree-sha1 = "8bb861136d2169d594a49ac9982bf0da5ab50519"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "c45b6fa4205be8010520edccb190a006b87b9cd8fdb93421c3b40cbda309e6c0"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "ac9dae538db66f84f05bc82edd56d3ccd12ac3bd"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "d1359a39d4772441fea75eb55dc61bb5b4fadf1a7f134faa687bb05808137da8"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "85fbbe71221ee900097fb58ea8ee25781f07835c"
os = "windows"

    [[LibUV.download]]
    sha256 = "11ff47024299cfb208a5247c6b94f1f0f5c2dea5103014a5b24cf46f147e09ab"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "b5c48b44342830eea3588ee409487e4eac56e93c"
os = "windows"

    [[LibUV.download]]
    sha256 = "9afd4cdae865e54dd40e9b2a6ddec3c71f931e86acc3167baa3dd21aa0b614c8"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.x86_64-w64-mingw32.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "eeb9f6db3677ac13a739effe89e867dcbfe53f7f"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "30da9a336e54d5f47fb8acc440ae4108ce4330b9e944c843235aca8d539ad152"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "b9ef84a37a7972b69461757cc32d1ee438f7542a"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "e91b392c15a279a7d107cff83b573457bec94160b37f00fecbeaf156bf86c875"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "fc20e53bb946578e7dedde68b7bed278dea6543d"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "7d8ea888a4ade9b617f6749d472712663c1bc7f6e24a329812a726940ddb0c59"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "1cd8fada430d624608798852dee0867de02876ed"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "1666fb3e62bc64e3764a99e7df646f4c0fb1f8960a9d0f0b8c5af57fc088e10a"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "eefe95aafee3b57957ad81315c5195fa7d233b50"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "45754428c3bf177f055f00b0c68b3d3cd61a7801a1d21aef55f1690556275fd8"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "7cf8b9dde2c50515850c5e033e32ca67a18264b8"
os = "macos"

    [[LibUV.download]]
    sha256 = "070c15ac5e4469a40588910c1d624487a0a660d0396e94d6237513cdce141e71"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.x86_64-apple-darwin14.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "caea0e671fd8689ca4731503b70f8f3007158097"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "bc93c6749fb620f304d7c231f1f2701acef609ab9145895797eba2a0c06095a6"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "cec2a02b4cc983ec35d3f7eb4d880fdb9c5e266b"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "0121f4275d7bfc94833c19fda6a49d761210293e680a77c410cb06670af7660e"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "244ac65057a80ab9c8b1a0c338e66a2057f6ab21"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "0b834ac8db649cc8015c875a5656f211d3acb167fbe0c431059cb1704612c769"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+3/LibUV.v2.0.0.x86_64-linux-musl.tar.gz"
