[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "8c1e56b3593d5b055b6fb172edf4fcf8fa6a57ba"
os = "macos"

    [[LibUV.download]]
    sha256 = "706cb0cfe8a96e1758bc1a8e04bad570a9c49ede6c6f2465ce1c70b2e685447e"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.aarch64-apple-darwin.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "3578ee4ad16eddf9b2beec98ddf5a3d3ca175aad"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "ab218dc1d24f981d290453a952a8ea30b5f9afb41bb1e634b6e9683fe71a3879"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "dd8cdcdebaf2135e7857abc8dc61cb209c67b205"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "1a7371377c5b1d6ee9b0bdd42e81218c5d71e06336a7c96d29478a1cceb39a30"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3518b7e1f144759cec73c2c684c4f2de7bdbcdeb"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "118b76b184e652c212cd40bc62282bb5ecc2003a20e985c52e2e7922ccfb4556"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb84c43edf69016861767faf0c87c342ce59567e"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "ac4d8ef3032994ad6d604b5a82f3c5cbaff38a9d397fa76152a20298b071161e"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.armv6l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb8790ba5754b54e89ca99e6b6b74539d013979e"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "5974c2a5601c0085c56390a9e728bd4eab70050e06ca54827c343be22bb3e023"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8892d461b1c732e773806edd3ccd16570fd2953f"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "2c59e8ff3cf20372083ac41a2884339bd866c775f5bf0ea42ca0c335282c0e82"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "cbc3b6e769b5f87a47a0b8d09781621a80e326d3"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "bdb881727eaecf760f526f816cf9ab382e71b59f796d2a94ebb3662e94cc892b"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "e4a6943d40137877df76a0385132259348310e60"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "c5955dacc4f682ce6599b200ca4220f198e174f2dfa7bc1f2e5a07a6e7bfd343"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "1254717823b48f151c3809fe5694fd316ff780a0"
os = "windows"

    [[LibUV.download]]
    sha256 = "b4561f3ce0483675ddb88e2e035233aeef993ce5cd1e051a3a295fb69d409f4a"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "a6af0b7ab30bf618f455eea4f1f1bad6da1c19cc"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "1418f76f3f80021e8f9a77097b2143034106b8176963b5fed7b6dfb290d5eeef"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "f9a905a97d0b1459039a238471a9f12f691fda9c"
os = "macos"

    [[LibUV.download]]
    sha256 = "d1a533283619cd2a74e1c429408b83220bb9aa7de2265276ea149c6c66674ab2"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.x86_64-apple-darwin.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "127882bab6797e106a88ec2d19b9cbd0ab99a84a"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "e5b01b6afb9d94d305de852f401f999c062b4e1fede11a13fe04b069306f1f5d"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "bce1f5024ee1222747068423765a2bbd53350e4f"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "85bf3cd18b2df33a3d5ebc317cf522b38bc71b78da14ccb05d02191a19aab339"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.x86_64-linux-musl.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "891151600b6bc940dd3fe72305f55ac3cc620593"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "744a7a5132e8d293d2855dcf8cbaf133be0c1d2bb887bd614134953b62a9c5ea"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.x86_64-unknown-freebsd.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "e7051db7729098d5c6529e0e7f06ccf3147570cf"
os = "windows"

    [[LibUV.download]]
    sha256 = "7f21320b73007f86769ecf7f1a5393f2751bc6217c073a0899d4b8e9349ff1c1"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+2/LibUV.v2.0.1.x86_64-w64-mingw32.tar.gz"
