[[LibUV]]
arch = "i686"
git-tree-sha1 = "14563fcb75593e3de1de65dfa0789c24ddb7d076"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "948733e0001910ecf0537679172e87bae7636b6d74e7b6dd77d319a9148c8dcf"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "7e7ec4e9380b19d9febe81819977a46bb7790f5f"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "f7cf86e311959c83fda117291c17914e74fc4f99a8dc75b22512a280b89e746b"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "0a46a4ca10751cbdf77a53d6b2fe5853d570d56d"
os = "windows"

    [[LibUV.download]]
    sha256 = "21d6e778bbc2ca9a7eae074e172e8fc1af8f60c8e4a3116ea3c1b246ef57f3e2"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "18935d0ec2477e41d869092981e079a1224cfe83"
os = "windows"

    [[LibUV.download]]
    sha256 = "c8efa8584268e53327e6a6a0dc85960ecb0a2bbbc1da5f3f34f524e4c99a4c63"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.x86_64-w64-mingw32.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "22b924ed7b259abf21f38ee9e16bcdf3264d35a2"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "39ce77199c535fe65b978f09ad62751a8e7cc7495c3b6ced2a75a27df001fe0d"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "21aec7d8a589eabba52ab11f94314e3e821f36db"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "1ddcecdd737eeb0419ec21ed002112a551e5d6effa219c472f77306141358928"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "afe33c54a72e1cb8b63ba59f8a6e1ac12184bff1"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "7bc8f3b8fa64f77e71d064c75a6a1982e6f50b9eb561183f93366e65bc5bdde1"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "c2b88eb63dffd257cb9c7007cab62894a2b90e6a"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "3590ba113255c0153d5b53a89c4ff6b48bae01ae18ff0c632f9b94927ce1f34f"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "d6f7c68bc3164ef1b3979f27ec0834e41f398805"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "1176251880a2c9842ca6de3c69b8a7d7b1d49e145aaa4af3f093eae13e39a305"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "0966b346f4d770cf43877bf45607743074fc7c29"
os = "macos"

    [[LibUV.download]]
    sha256 = "7c9e43cae58c99224a5c5a085c23a457e6ffb328bb38dcd2adc487c8b6440233"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.x86_64-apple-darwin14.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "48b37ac1c20e11206028e6aa9d09ebba175d7922"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "fb8c41bebafda03a7e708a6c3948e6fe9ae94f25e1032b35ad867d2df95a4bf6"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "74a4b7a1092e648d68152e19ebe90f61f3324675"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "23d75c0d2c7910c80bd689f9010002237fba7a6842ee9b54f51b2f5404924327"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "2c0177715e845cf7a857a8132992186ad5652071"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "a2bbe435897ad951f03bc74d7f6dd410c50685daf8a51ad53b516d25e0fe1e1f"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+2/LibUV.v2.0.0.x86_64-linux-musl.tar.gz"
