[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "b3428fc9152d03d9e1c909757db165b3aa3d8778"
os = "macos"

    [[LibUV.download]]
    sha256 = "c67618d157e36181912e15bd8fd151d5993adb543a5087b3df29c788f802a49a"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.aarch64-apple-darwin.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "f0048fb2a24cc022bb9d72593028a9a5cd1007b9"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "d7376bee97f3dcdb7587a16d6bda66aa9f656b1b347b05e95d1d01810995abd9"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "28ff6c392f1b96c4ca457a86e9af80ce528793d1"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "6e799ce8679c4f03973906b3aca062617cef49e53c5ffff1ad1ecd6dc5918661"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f3f8296173abd8662388619af3ef648da66540e"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "971dc07ba6525b14444d85991932e75157830f585465b9d5140ce4aacb4fcf19"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a10259fdb467ed2598a5c46ae1270646a32f0ad0"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "723e0c9512f7c3617cd345057030c263fe151cd79984e3a626492b134188359f"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.armv6l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d44ce9674a1b39143b102659e1f0ba8b1d7ad06a"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "680114ea8ed6746d7f83ae2fbf7e5f0f277f8ca767926a89c29d021afe280a83"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "abd85eba581eebbac4f2e24a6d31768c204f5a89"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "6408af9caf7edf8a0d12e642c183b3242fe03609a1aa3ee8fc1803c92e6a4df8"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "e576bde9ee3e6d2afccd271a4757c479f5fa1eab"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "4a7ed7bae1f7dab4b14826f53617529af41b07db538c4b4460fa538a505e6364"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "6b7ded5ccd49a2aea632cace5ca4877b1c2b6220"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "6874ea766a5436742b6681658a4862ad513b346f94d0fa8c68de41286a0b3ee9"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "f4e5f1593909276c8d123350c600d9f753debffb"
os = "windows"

    [[LibUV.download]]
    sha256 = "9003d9773becf60ce7c3794c0a3488dfdfea8c7c00283e258d68b439ec672609"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "3c5135bf68f52496af98f4a9630ea32c3a6e7d09"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "4bce54cd16ce5b0623febbbd72e6fe95f56725812f352347fd3b319560698380"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "9b045fcaced378abcbb00de0da56a52aa54acdb3"
os = "macos"

    [[LibUV.download]]
    sha256 = "a8afe58f5459ddb5e3d4e44825773fe914d328b0ce31024c59eb8a8b7cc9214e"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.x86_64-apple-darwin.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "ae5bba436cee9fc2fe8ac2033cbfe75cd83bee42"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "267c2e68bfea5d34b7a52775f16d40ad4a71722b5e07ebe3966fa51ec6585b77"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "f8162f809bf7d350a505d2da7026c69d9f8eb549"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[LibUV.download]]
    sha256 = "4c23987fb4cdf70b8ae455938e137655a94f5eb6ff7625e22778c2255a8e7a93"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "cdd6a1f95e62375efe2a3bd6c3781d3784964162"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "e9477f8591e34f8ef73f99aec5f0d8b05962abbef8ef734e8a392512f0760990"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.x86_64-linux-musl.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "e465016a5223c32e7cb5c80f98d15cd24e1e799d"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "d25714df6f72c0b7e82ee933d9deeeb9d234533913c4eac4c8bbe61cb145ef23"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.x86_64-unknown-freebsd.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "b9cf466c7e7ee1898b9f799121b7975431299dc8"
os = "windows"

    [[LibUV.download]]
    sha256 = "896e5826f2db123aaf91f84b5ee43e6e86ebfe394f32ce3936f38fbf1ee239f4"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+10/LibUV.v2.0.1.x86_64-w64-mingw32.tar.gz"
