[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "d6c88f1288a42a63bc1dac687ea9a164f68f4f13"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "2c38ef842870c88e06fbc33525765d5489473cd32e7bbe890030368d59aa2137"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "4f579f0a4ddec028902741e3b265755d182b161d"
os = "windows"

    [[LibUV.download]]
    sha256 = "044c976ecbc9a7802fcabca9080b4f7f2fc4923a53227964aa7f0c3f1fcf5528"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "88a7d9117a8a4f6433c07305345a22a90fdbd74a"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "82238367501736f17f7ccc6dd058e3ca4673080c76cb1a74777060bf9e9fe04c"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.x86_64-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "fc4da215f6e6e9f198e68151fb9e0839f8f44023"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "e81b02da4e9d8c3e7cc21a65bf9106d18d486842f51420ca9cf8c0a9ef9d133a"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "a4a01192562ca842115fba44bde22658338422b7"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "535753d2ac16dd448250476e22c18dc53d627ec88b23b90f57544b0ea8e1d0ac"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "eb96e5b66c7dcc7d2a9446d104cdbfb870e062d7"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "ffe86954ccc3e5526709aebe9d92b34554c3f6f0cfe5522ae8dbbc70e3e7cbbb"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "0915f650d6d4cd5eaafa7e2e42496ee844d2fdb8"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "6c5396c5d85876784b6494235a55d58b5f5d8d9560fcea2f74edde1928005661"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "72c0b718bcd55104248d6c0f7b00a615c5ea79ee"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "c430bc6fd6f232af6bba51e9ba7a13de3d9f0307e82bbe9ad6d3f6a42dd08ba7"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "bad82b526d8b515372d08d13173b27e00bb6dcab"
os = "macos"

    [[LibUV.download]]
    sha256 = "950189faea2f49156255e80d052c311ab233066a43866d6530e39932c3fe77b1"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.x86_64-apple-darwin14.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "8e53b3483e81519a6d8931a5ab313b44338b246d"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "6e543a99180740486c2449b7a857c07944c178c5a5aada45a764e7d94ad8b884"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "71283dd8e8cd432373f9916649f2e6d16d5c62e1"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "4b57ac21f867c852ba5103d51070de5e23bf1481456dc334ddc59a78ee181cb3"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "6a108db5b57e5c62598695aa9af63a51b26207ff"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "2a388a453ec744f00b10157157679926820c6731b12b49f4a7080181e341e1d5"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "5a418401dfc1ebdcc31445eae42715170ee6c3ea"
os = "windows"

    [[LibUV.download]]
    sha256 = "42bd6bff1507cecab38c1a35cfc230ac8d37393b4d6e84f0315905303231b24d"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+1/LibUV.v2.0.0.x86_64-w64-mingw32.tar.gz"
