[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "13343c84257195b7d5ea68b506590ed80ca6cedc"
os = "macos"

    [[LibUV.download]]
    sha256 = "be90357b32b9d4d03dca56d2875f60f7eb49651e6386a3b85ca35886b7e0c4dc"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.aarch64-apple-darwin.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "d29b2d332109638c1d1ad80e74818d26d807a5c1"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "d5ef731b3508bc06de5149cde7e0bd9aa9f32e1f4c2a6b42f85da085c248290d"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "f7caaf924e610675281b1e44e82647de3ae3f1d5"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "f726888c11bc52bed2823bfc8ff896911a97e5e71a27a0d626378de6c72b64b6"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ebdec5a4b52fabfbedc6e4c89340df399a5f282b"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "8d500d1ae67f19f4d4890ba1f3feaf0bf4ae870ea6b39e12b2ea7bf52cc7863c"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5a1f65e4f6dfc52abb7ae735b3c9c58bfa2bdb82"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "cc55319ef1cd924c1e05f46834532f4cd64ad7f1b6bbf82c102cfd457f749593"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.armv6l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "595d66e0dee42a35142b680b15f818a7265048f3"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "902172e52cf7290826c335ad5845cb8f64d5403da6c03e862bf2a6fe12e742f2"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1cecb24f1dddc78da372a0adf4dc1f7cd9e2a531"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "7370753d74554fe22efda0c9b5d906ccdec820663e5d1a4e2b8bbd78eabb4231"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "5304254e02e81836f8bdb95390095bb78989c31d"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "3161322787f09bbd8adb16444d39f81a292e32d9cb828e04942b88b0a18578ce"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "7eba1fb6c36e6307592089bf37fbbcd56ed0fb30"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "bbb25b37c326eff0d63ac8f31b22212607c740a1b84570ad3e1b99b487cee758"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "7cc91cd2aa20398972aca64f7255f5fda9e39aef"
os = "windows"

    [[LibUV.download]]
    sha256 = "b7a020e0a6c752fa990b59e81533581e12f6de8f6956b8096b024629c57c0ed6"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "cfb773c7ace24a23e0481b5b28a5ba9cd22d6e3e"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "786832b088c0258606b90f4d4c768d702248fc514e9db48041d901bdc907fdbb"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "eee05d01858ba2fbd30204e29c707b242b2cfeae"
os = "macos"

    [[LibUV.download]]
    sha256 = "dc0c4c109830026df42ae93be791c01814dcebbec8610183a965f01ef9c97447"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.x86_64-apple-darwin.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "eb8f949cec4953f9b997bce8ed786f1b2f922f01"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "ae2ef986fa48b284b39d8c6230912c2261513bb507f3265de4e655217451a101"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "d7ee44ff417dcc2e00cc6c286abebbbfc1683b11"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "72729bc343add9759f768f0ead16e24ed6bd145cda5235cebd361a1575721893"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.x86_64-linux-musl.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "628ebc35e4898b3a51d1ff3b5ca01211f84ea004"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "ce10ccd1d6d367503250763fb49993efa9dcb944cab5f56788f6c9311fffe25c"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.x86_64-unknown-freebsd.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "a45cb6af55a15208ecb349e846317d45f53e7bac"
os = "windows"

    [[LibUV.download]]
    sha256 = "4f9513610e8fc0980e6a100919caf4fac85c582e8365ae96ce5c37cbf4368bfd"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+6/LibUV.v2.0.1.x86_64-w64-mingw32.tar.gz"
