[[LibUV]]
arch = "i686"
git-tree-sha1 = "66a716214b8f8c4a1ae85a7fc5f847394db60561"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "dbdb6f7f046d917274480cd1be9d39e999c784eb51bbb3a96243d730b736e1ec"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "7bd48ff858e147530b8c29de2a8fc18a78453c5b"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "bb30b792b9924dc346d3a102318197a35d2cb69a1caa17b862663d838a235b56"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "0b6cdb6dffbb333a506da78305d35100b29acad4"
os = "windows"

    [[LibUV.download]]
    sha256 = "a13ae7f8f153d9fa7eb035e4626b0dcbe229d7567bea07f9ca768b0ce025b984"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "326ba7731d350017d1e6db409ae1191372d3a54d"
os = "windows"

    [[LibUV.download]]
    sha256 = "68306af18c2639ca12f6cb6be9850be787501187d08b70fb6ab6e1d7f16f24ab"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.x86_64-w64-mingw32.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "7444eca08dc9e72cf7b2d056066a3f828545d3e0"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "3ef67ce9773ee65915139b18784bc61ce7dff3242d47da6c9ed8f39e0a2de844"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
git-tree-sha1 = "6c03ed5637085d4b62b6934b9dbbd5c8ff9a3c6e"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "95a6ae921c9ce4c8376114351e0e116710457e2060175b23d348f519a91b2dfe"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "ba0fcd2742a52fe8164f3e6720adfad18bd9d2ce"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "ec07233c3e9609874b0bdbd8e91e2d6d222dbc0dddffe4ead00d75e4e4438ab8"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "dd94f429a0d19c0059aad48f03f67c0c52e33285"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "bd6d7efd0f3e6156bb23edf35895b54b2dbbc1b4fc1948b7a83d2f511578c0b9"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "c7be4d4bc86b49317019caf4b6a712c1c1b08436"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "5f2256e7aabc30a993adcbd994ec66c0be81bc5c2d5d3e0ee27d5e519346047a"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "37750b0214c01bda40b2689b6fee02a197656bfc"
os = "macos"

    [[LibUV.download]]
    sha256 = "3537612337f4241098f420d15d4096c8856e0af4b1df282c4e3664a419ca77f3"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.x86_64-apple-darwin14.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "4ddc150018a56cb9b9e531821538cb4f1f7cfbad"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "260c1fee45b96ad8fee32b575240d9168653b309dbdaddfe85257ceda77e63b8"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "0ad9f0690ab89dec1c95cebc9e775d0a0e2c8b8a"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "cee958f8209ceb11946b058dc48af07db25af3b04c15a13a7eeef51f704895aa"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "dc1cb09b7194c9297593f9cfcb9492cfe6062302"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "54e6641f3da7fc431eae028ce8210bc968622a52792530361b50f832264cb5d8"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.0+4/LibUV.v2.0.0.x86_64-linux-musl.tar.gz"
