[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "adbb1c71afe0e49bf9b0994463fa35bfd4eb1a05"
os = "macos"

    [[LibUV.download]]
    sha256 = "757dbd95c5340495a2adb1b1d68bfcc2c67229d659e82d15d36ab36990843ca0"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.aarch64-apple-darwin.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "84399e0c17a7198f58d86007e4fa01d7906c5fa1"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "ec3d15ae426e61421d4217a3dc8ceeb1ec86448e7e009db750b038612c9cd951"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.aarch64-linux-gnu.tar.gz"
[[LibUV]]
arch = "aarch64"
git-tree-sha1 = "97389b91c772cdeff3ac3764d6b8bffd86b72e52"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "88cd0e0d533ac1924524f7341cbdd81ab9bb9fc44a716024c6b78586c9ddc4e1"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.aarch64-linux-musl.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f20554e849d2dc9f2d0ed71735f6bd20e203c42"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "24883761bdcf69b515368f44781c2cd69b320a57eb9b336fb48f3d8bbe55ca3a"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.armv6l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dd6bbc7756e0a4bb76d3d402f6a7e549a896889f"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "817df3d574054f812f0118dc42d271816731bbfb323696a9766ad753b92b3aeb"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.armv6l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d6aa38dbc439a6f4639d602c4485e28cdac6e93e"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "3577fa7f5e6792ba24b4065046e05964714244e237596b1647d9a58fd88f8668"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.armv7l-linux-gnueabihf.tar.gz"
[[LibUV]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40d2d1a743e1df470c8e4e119598e4115ec7f246"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "f3246959530616ebe62d801e9ec7a65f17742be779e910827ef0776f2e2842ca"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.armv7l-linux-musleabihf.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "bd4a3819b826e97323d725bf5631840860b73a6a"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "7f0dbbee7e50d6f5523fadd513f0adfb4ff037e67fdd7d4d8e0e44532d3ec21f"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.i686-linux-gnu.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "51aa936ffe500ec0630f278a876d406a52fd8067"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "0bddd119927c822658156ca0a056536e51204665abb4a99c87310c15e86d40c8"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.i686-linux-musl.tar.gz"
[[LibUV]]
arch = "i686"
git-tree-sha1 = "0702234560803490dc5f0f15ed8aa94e8b380ece"
os = "windows"

    [[LibUV.download]]
    sha256 = "3bcbff31ca095afb8928b1e29a045abb234b9b43676f7d16133aabbb3bfca036"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.i686-w64-mingw32.tar.gz"
[[LibUV]]
arch = "powerpc64le"
git-tree-sha1 = "208a2780170b41511b89e482041af45743f17eb3"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "e69d9c9588ed9b49480b22846b3c680354b989c10a13519f20b2b40d3dd998a0"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.powerpc64le-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "b6ef4c53a4ba4ba511674701eb48a689f58a8b21"
os = "macos"

    [[LibUV.download]]
    sha256 = "09e57d596a9457b7aea5ee5ddb67f956c3f2b1f101d1ebea38d5c9198621ee26"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.x86_64-apple-darwin.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "7b1d28c0514578733831f048130bc8d1fa1277b6"
libc = "glibc"
os = "linux"

    [[LibUV.download]]
    sha256 = "c83d9d7e089a5432e38b736e0a72286a52206297737f0543ac20bfc92cdcc4aa"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.x86_64-linux-gnu.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "a12419e5f1a1f543d1166464388de5f2adb4f8a4"
libc = "musl"
os = "linux"

    [[LibUV.download]]
    sha256 = "17c08a3c86b51ee754c117b90328e5c91ec1ceb46c5d4f44c452ab96c5c3fd6d"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.x86_64-linux-musl.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "2da9bba7cad6f1c337624c84b2661eebb6ffdffe"
os = "freebsd"

    [[LibUV.download]]
    sha256 = "a44a543c71590cdd3e12de4af4c73c64ebb65fab4ab9d2802a3eac0d51eb416c"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.x86_64-unknown-freebsd.tar.gz"
[[LibUV]]
arch = "x86_64"
git-tree-sha1 = "b70c48c1f479036032d9d38637b3099950eeefe1"
os = "windows"

    [[LibUV.download]]
    sha256 = "4d31f06320d68cb4f6ecc31efbc98bf01e1b90ce50f76839005d949200c55d75"
    url = "https://github.com/JuliaBinaryWrappers/LibUV_jll.jl/releases/download/LibUV-v2.0.1+8/LibUV.v2.0.1.x86_64-w64-mingw32.tar.gz"
